Traceback (most recent call last):
  File "/home/yerinyoon/.local/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 969, in _finalize_columns_and_data
    columns = _validate_or_indexify_columns(contents, columns)
  File "/home/yerinyoon/.local/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 1017, in _validate_or_indexify_columns
    raise AssertionError(
AssertionError: 40 columns passed, passed data had 2 columns
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/yerinyoon/code/anonymousNet/starGAN/stargan.py", line 184, in <module>
    main(config)
  File "/home/yerinyoon/code/anonymousNet/starGAN/stargan.py", line 72, in main
    celeba_loader=get_loader(config.celeba_image_dir, config.attr_path, config.selected_attrs,
  File "/home/yerinyoon/code/anonymousNet/data/celeba/data_extract.py", line 107, in get_loader
    dataset = CelebA(image_dir, attr_path, selected_attrs, all_attrs, transform, mode)
  File "/home/yerinyoon/code/anonymousNet/data/celeba/data_extract.py", line 35, in __init__
    self.preprocess()
  File "/home/yerinyoon/code/anonymousNet/data/celeba/data_extract.py", line 78, in preprocess
    self.full_label=pd.DataFrame(self.full_label, columns=self.all_attrs)
  File "/home/yerinyoon/.local/lib/python3.10/site-packages/pandas/core/frame.py", line 746, in __init__
    arrays, columns, index = nested_data_to_arrays(
  File "/home/yerinyoon/.local/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 510, in nested_data_to_arrays
    arrays, columns = to_arrays(data, columns, dtype=dtype)
  File "/home/yerinyoon/.local/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 875, in to_arrays
    content, columns = _finalize_columns_and_data(arr, columns, dtype)
  File "/home/yerinyoon/.local/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 972, in _finalize_columns_and_data
    raise ValueError(err) from err
ValueError: 40 columns passed, passed data had 2 columns