Traceback (most recent call last):
  File "/home/yerinyoon/code/anonymousNet/starGAN/stargan.py", line 278, in <module>
    main(config)
  File "/home/yerinyoon/code/anonymousNet/starGAN/stargan.py", line 72, in main
    celeba_loader=get_loader(config, config.celeba_image_dir, config.attr_path,
  File "/home/yerinyoon/code/anonymousNet/data/celeba/data_extract.py", line 141, in get_loader
    dataset = CelebA(image_dir, attr_path, all_attrs, transform, config)
TypeError: CelebA.__init__() missing 1 required positional argument: 'config'