Finished preprocessing the CelebA dataset...
200600
torch.cuda.is_available(): True
torch.cuda.get_device_name(): NVIDIA RTX A6000
Finished preprocessing the CelebA dataset...
200600
Loading the trained models from step 3000...
Traceback (most recent call last):
  File "/home/yerinyoon/code/anonymousNet/starGAN/stargan.py", line 165, in <module>
    main(config)
  File "/home/yerinyoon/code/anonymousNet/starGAN/stargan.py", line 87, in main
    solver.train(config)
  File "/home/yerinyoon/code/anonymousNet/starGAN/model.py", line 379, in train
    self.restore_model(self.resume_iters)
  File "/home/yerinyoon/code/anonymousNet/starGAN/model.py", line 219, in restore_model
    self.G.load_state_dict(torch.load(G_path, map_location=lambda storage, loc: storage))
  File "/home/yerinyoon/anaconda3/envs/pytorch/lib/python3.10/site-packages/torch/serialization.py", line 771, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/yerinyoon/anaconda3/envs/pytorch/lib/python3.10/site-packages/torch/serialization.py", line 270, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/yerinyoon/anaconda3/envs/pytorch/lib/python3.10/site-packages/torch/serialization.py", line 251, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/home/yerinyoon/code/anonymousNet/sevice_model_save_point/3000-G.ckpt'